/* Iniziative di esempio: servono a provare il funzionamento del portale.
   Nessuno di questi enti, numeri o appuntamenti e reale.
   chiude: ultimo giorno utile, in formato anno-mese-giorno.
   posti: presente solo dove la disponibilita e limitata. */
window.INIZIATIVE = [
  { reg: "Lombardia", tipo: "Cervice uterina", titolo: "HPV test ad accesso libero", ente: "ASST Santi Paolo e Carlo", dove: "Consultorio di via Pichi, Milano", quando: "fino al 6 settembre 2026", chi: "donne dai 25 ai 64 anni", tel: "02 8184 1", stato: "gratuito", chiude: "2026-09-06", posti: "ultimi posti" },
  { reg: "Lazio", tipo: "Melanoma", titolo: "Ultimi giorni: controllo dei nei", ente: "IFO Regina Elena", dove: "Via Elio Chianesi 53, Roma", quando: "fino all’ 8 settembre 2026", chi: "adulti di ogni età", tel: "06 5266 1", stato: "gratuito", chiude: "2026-09-08" },
  { reg: "Veneto", tipo: "Mammografico", titolo: "Mammografia, ultime date utili", ente: "IOV Istituto Oncologico Veneto", dove: "Via Gattamelata 64, Padova", quando: "fino al 9 settembre 2026", chi: "donne dai 50 ai 69 anni", tel: "049 821 5849", stato: "gratuito", chiude: "2026-09-09" },
  { reg: "Lombardia", tipo: "Mammografico", titolo: "Mammografia gratuita over 50", ente: "ASST Sette Laghi", dove: "Ospedale di Circolo, Varese", quando: "dal 5 al 30 settembre 2026", chi: "donne dai 50 ai 69 anni", tel: "0332 278 100", stato: "gratuito", chiude: "2026-09-30" },
  { reg: "Lombardia", tipo: "Mammografico", titolo: "Unità mobile in piazza", ente: "LILT Milano", dove: "Piazza Castello, Milano", quando: "12 e 13 settembre 2026", chi: "donne dai 45 anni", tel: "02 4952 1", stato: "gratuito", chiude: "2026-09-13" },
  { reg: "Lombardia", tipo: "Prostata", titolo: "Giornata della prostata", ente: "Fondazione Poliambulanza", dove: "Via Bissolati 57, Brescia", quando: "19 settembre 2026", chi: "uomini dai 50 anni", tel: "030 351 5555", stato: "a pagamento", chiude: "2026-09-19", posti: "ultimi posti" },
  { reg: "Lombardia", tipo: "Colon-retto", titolo: "Kit colon-retto in farmacia", ente: "ATS Città Metropolitana", dove: "Farmacie aderenti, Milano", quando: "tutto settembre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "02 8578 1", stato: "su invito", chiude: "2026-09-30" },
  { reg: "Lombardia", tipo: "Melanoma", titolo: "Controllo dei nei", ente: "IRCCS Policlinico San Matteo", dove: "Viale Golgi 19, Pavia", quando: "24 e 25 settembre 2026", chi: "adulti di ogni età", tel: "0382 501 1", stato: "gratuito", chiude: "2026-09-25", posti: "ultimi posti" },

  { reg: "Lombardia", tipo: "Polmone", titolo: "Screening polmonare per forti fumatori", ente: "Istituto Nazionale dei Tumori", dove: "Via Venezian 1, Milano", quando: "iscrizioni fino al 15 ottobre 2026", chi: "fumatori e ex fumatori dai 55 ai 75 anni", tel: "02 2390 1", stato: "gratuito", chiude: "2026-10-15" },
  { reg: "Lombardia", tipo: "Osteoporosi", titolo: "Densitometria ossea in giornata", ente: "ASST Papa Giovanni XXIII", dove: "Piazza OMS 1, Bergamo", quando: "6 e 7 ottobre 2026", chi: "donne dai 60 anni", tel: "035 267 111", stato: "a pagamento", chiude: "2026-10-07", posti: "ultimi posti" },
  { reg: "Lazio", tipo: "Polmone", titolo: "TAC a bassa dose per fumatori", ente: "Policlinico Umberto I", dove: "Viale del Policlinico 155, Roma", quando: "iscrizioni fino al 10 ottobre 2026", chi: "fumatori dai 55 ai 75 anni", tel: "06 4997 1", stato: "gratuito", chiude: "2026-10-10" },
  { reg: "Toscana", tipo: "Osteoporosi", titolo: "Giornata dell’osteoporosi", ente: "AOU Careggi", dove: "Largo Brambilla 3, Firenze", quando: "20 ottobre 2026", chi: "donne dai 55 anni e uomini dai 65", tel: "055 794 111", stato: "gratuito", chiude: "2026-10-20" },
  { reg: "Veneto", tipo: "Colon-retto", titolo: "Consegna kit colon-retto", ente: "ULSS 3 Serenissima", dove: "Farmacie aderenti, Venezia", quando: "tutto settembre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "041 260 8111", stato: "su invito", chiude: "2026-09-30" },
  { reg: "Veneto", tipo: "Cervice uterina", titolo: "Pap test senza prenotazione", ente: "ULSS 6 Euganea", dove: "Consultorio di via Ospedale, Padova", quando: "ogni martedì di settembre 2026", chi: "donne dai 25 ai 64 anni", tel: "049 821 4111", stato: "gratuito", chiude: "2026-09-29" },
  { reg: "Veneto", tipo: "Tiroide", titolo: "Ecografia tiroidea di controllo", ente: "Associazione Amici della Tiroide", dove: "Piazza Bra, Verona", quando: "10 ottobre 2026", chi: "adulti dai 40 anni", tel: "045 807 1111", stato: "a pagamento", chiude: "2026-10-10" },

  { reg: "Piemonte", tipo: "Mammografico", titolo: "Prevenzione Serena: mammografia", ente: "ASL Città di Torino", dove: "Presidio Valletta, Torino", quando: "dal 1º al 31 ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "011 566 1566", stato: "su invito", chiude: "2026-10-31" },
  { reg: "Piemonte", tipo: "Colon-retto", titolo: "Sangue occulto: ritiro e riconsegna", ente: "ASL CN1", dove: "Farmacie della provincia, Cuneo", quando: "tutto ottobre 2026", chi: "uomini e donne dai 58 ai 69 anni", tel: "0171 450 111", stato: "gratuito", chiude: "2026-10-31" },
  { reg: "Piemonte", tipo: "Melanoma", titolo: "Giornata del neo", ente: "LILT Novara", dove: "Corso Mazzini 18, Novara", quando: "3 ottobre 2026", chi: "adulti di ogni età", tel: "0321 35 404", stato: "gratuito", chiude: "2026-10-03", posti: "ultimi posti" },

  { reg: "Emilia-Romagna", tipo: "Mammografico", titolo: "Mammografia con accesso serale", ente: "AUSL Bologna", dove: "Poliambulatorio Zanolini, Bologna", quando: "dal 14 al 26 settembre 2026", chi: "donne dai 45 ai 74 anni", tel: "051 649 4444", stato: "su invito", chiude: "2026-09-26" },
  { reg: "Emilia-Romagna", tipo: "Cervice uterina", titolo: "HPV test in consultorio", ente: "AUSL Romagna", dove: "Consultorio di via Fiume, Rimini", quando: "settembre e ottobre 2026", chi: "donne dai 30 ai 64 anni", tel: "0541 707 111", stato: "gratuito", chiude: "2026-10-31" },
  { reg: "Emilia-Romagna", tipo: "Polmone", titolo: "Screening polmone per forti fumatori", ente: "Azienda Ospedaliero-Universitària di Modena", dove: "Policlinico, Modena", quando: "iscrizioni fino al 30 settembre 2026", chi: "fumatori dai 55 ai 75 anni", tel: "059 422 2111", stato: "gratuito", chiude: "2026-09-30" },

  { reg: "Toscana", tipo: "Colon-retto", titolo: "Kit colon-retto in farmacia", ente: "Azienda USL Toscana Centro", dove: "Farmacie aderenti, Firenze", quando: "tutto settembre 2026", chi: "uomini e donne dai 50 ai 70 anni", tel: "055 693 4111", stato: "su invito", chiude: "2026-09-30" },
  { reg: "Toscana", tipo: "Mammografico", titolo: "Mammografia in unità mobile", ente: "ISPRO", dove: "Piazza dei Miracoli, Pisa", quando: "22 e 23 settembre 2026", chi: "donne dai 50 ai 69 anni", tel: "055 3269 1", stato: "gratuito", chiude: "2026-09-23" },
  { reg: "Toscana", tipo: "Prostata", titolo: "Open day urologia", ente: "Azienda Ospedaliera Universitària Senese", dove: "Le Scotte, Siena", quando: "17 ottobre 2026", chi: "uomini dai 50 anni", tel: "0577 585 111", stato: "gratuito", chiude: "2026-10-17", posti: "ultimi posti" },

  { reg: "Lazio", tipo: "Cervice uterina", titolo: "HPV test senza prenotazione", ente: "ASL Roma 1", dove: "Casa della Salute, via Plinio, Roma", quando: "ogni giovedì di settembre 2026", chi: "donne dai 25 ai 64 anni", tel: "06 6835 1", stato: "gratuito", chiude: "2026-09-24" },
  { reg: "Lazio", tipo: "Mammografico", titolo: "Mammografia over 45", ente: "ASL Roma 2", dove: "Ospedale Sant’Eugenio, Roma", quando: "dal 7 al 25 settembre 2026", chi: "donne dai 45 ai 74 anni", tel: "06 5100 1", stato: "su invito", chiude: "2026-09-25" },
  { reg: "Lazio", tipo: "Melanoma", titolo: "Controllo dei nei in piazza", ente: "LILT Latina", dove: "Piazza del Popolo, Latina", quando: "5 ottobre 2026", chi: "adulti di ogni età", tel: "0773 664 141", stato: "gratuito", chiude: "2026-10-05", posti: "ultimi posti" },

  { reg: "Campania", tipo: "Mammografico", titolo: "Ottobre rosa: mammografia gratuita", ente: "ASL Napoli 1 Centro", dove: "Presidio Loreto Crispi, Napoli", quando: "tutto ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "081 254 1111", stato: "gratuito", chiude: "2026-10-31" },
  { reg: "Campania", tipo: "Colon-retto", titolo: "Consegna kit colon-retto", ente: "ASL Salerno", dove: "Distretto 66, Salerno", quando: "dal 15 settembre al 15 ottobre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "089 693 1111", stato: "su invito", chiude: "2026-10-15" },

  { reg: "Puglia", tipo: "Cervice uterina", titolo: "Pap test in consultorio", ente: "ASL Bari", dove: "Consultorio di Japigia, Bari", quando: "settembre 2026", chi: "donne dai 25 ai 64 anni", tel: "080 584 2111", stato: "gratuito", chiude: "2026-09-30" },
  { reg: "Puglia", tipo: "Prostata", titolo: "Visita urologica di controllo", ente: "LILT Lecce", dove: "Via Cicolella 3, Lecce", quando: "12 ottobre 2026", chi: "uomini dai 45 anni", tel: "0832 308 505", stato: "a pagamento", chiude: "2026-10-12" },

  { reg: "Sicilia", tipo: "Mammografico", titolo: "Mammografia in unità mobile", ente: "ASP Palermo", dove: "Piazza Politeama, Palermo", quando: "18 e 19 settembre 2026", chi: "donne dai 50 ai 69 anni", tel: "091 703 1111", stato: "gratuito", chiude: "2026-09-19", posti: "ultimi posti" },
  { reg: "Sicilia", tipo: "Tiroide", titolo: "Settimana della tiroide", ente: "Policlinico Rodolico-San Marco", dove: "Via Santa Sofia 78, Catania", quando: "dal 26 al 30 ottobre 2026", chi: "adulti dai 35 anni", tel: "095 378 1111", stato: "gratuito", chiude: "2026-10-30" },

  { reg: "Sardegna", tipo: "Colon-retto", titolo: "Kit colon-retto nelle farmacie", ente: "ASL Cagliari", dove: "Farmacie aderenti, Cagliari", quando: "tutto settembre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "070 609 3111", stato: "su invito", chiude: "2026-09-30" },
  { reg: "Sardegna", tipo: "Melanoma", titolo: "Giornata del melanoma", ente: "AOU Sassari", dove: "Viale San Pietro 43, Sassari", quando: "9 ottobre 2026", chi: "adulti di ogni età", tel: "079 228 211", stato: "gratuito", chiude: "2026-10-09", posti: "ultimi posti" },

  { reg: "Liguria", tipo: "Mammografico", titolo: "Mammografia serale", ente: "ASL 3 Genovese", dove: "Ospedale Villa Scassi, Genova", quando: "dal 21 settembre al 3 ottobre 2026", chi: "donne dai 50 ai 74 anni", tel: "010 849 1", stato: "su invito", chiude: "2026-10-03" },
  { reg: "Liguria", tipo: "Prostata", titolo: "Open day prostata", ente: "Ospedale Santa Corona", dove: "Viale Martiri del Deserto 80, Pietra Ligure", quando: "15 ottobre 2026", chi: "uomini dai 50 anni", tel: "019 623 1", stato: "gratuito", chiude: "2026-10-15" },

  { reg: "Marche", tipo: "Colon-retto", titolo: "Sangue occulto: ritiro kit", ente: "AST Ancona", dove: "Farmacie aderenti, Ancona", quando: "settembre e ottobre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "071 870 5711", stato: "su invito", chiude: "2026-10-31" },
  { reg: "Marche", tipo: "Cervice uterina", titolo: "HPV test in consultorio", ente: "AST Pesaro Urbino", dove: "Consultorio di via Nanterre, Pesaro", quando: "ogni mercoledì di ottobre 2026", chi: "donne dai 30 ai 64 anni", tel: "0721 424 1", stato: "gratuito", chiude: "2026-10-28" },

  { reg: "Friuli-Venezia Giulia", tipo: "Mammografico", titolo: "Mammografia con accesso diretto", ente: "ASU Giuliano Isontina", dove: "Ospedale Maggiore, Trieste", quando: "dal 1º al 20 ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "040 399 1111", stato: "su invito", chiude: "2026-10-20" },
  { reg: "Umbria", tipo: "Colon-retto", titolo: "Kit colon-retto in farmacia", ente: "USL Umbria 1", dove: "Farmacie aderenti, Perugia", quando: "tutto ottobre 2026", chi: "uomini e donne dai 50 ai 74 anni", tel: "075 541 1", stato: "su invito", chiude: "2026-10-31" },
  { reg: "Abruzzo", tipo: "Mammografico", titolo: "Mammografia in unità mobile", ente: "ASL Pescara", dove: "Piazza Salotto, Pescara", quando: "8 e 9 ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "085 425 1", stato: "gratuito", chiude: "2026-10-08", posti: "ultimi posti" },
  { reg: "Calabria", tipo: "Cervice uterina", titolo: "Pap test senza prenotazione", ente: "ASP Reggio Calabria", dove: "Consultorio di via Willermin, Reggio Calabria", quando: "settembre 2026", chi: "donne dai 25 ai 64 anni", tel: "0965 347 1", stato: "gratuito", chiude: "2026-09-30" },
  { reg: "Trentino-Alto Adige", tipo: "Colon-retto", titolo: "Consegna kit colon-retto", ente: "APSS Trento", dove: "Farmacie aderenti, Trento", quando: "tutto settembre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "0461 904 111", stato: "su invito", chiude: "2026-09-30" },
  { reg: "Basilicata", tipo: "Mammografico", titolo: "Mammografia gratuita", ente: "ASP Potenza", dove: "Ospedale San Carlo, Potenza", quando: "dal 12 al 24 ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "0971 613 111", stato: "gratuito", chiude: "2026-10-24" },
  { reg: "Sicilia", tipo: "Colon-retto", titolo: "Kit colon-retto nei distretti", ente: "ASP Messina", dove: "Distretto di via La Farina, Messina", quando: "ottobre 2026", chi: "uomini e donne dai 50 ai 69 anni", tel: "090 361 1", stato: "su invito", chiude: "2026-10-31" },
  { reg: "Puglia", tipo: "Mammografico", titolo: "Mammografia in ospedale", ente: "ASL Foggia", dove: "Ospedale Masselli-Mascia, San Severo", quando: "dal 5 al 16 ottobre 2026", chi: "donne dai 50 ai 69 anni", tel: "0881 884 111", stato: "su invito", chiude: "2026-10-16" }
];
