/* Le sei pagine screening: TUTTI i testi (SENTINEL, 25/09/2026, brief LORI §1.3-§1.4).
   Ogni stringa e copiata alla lettera dai file di copy approvati da Davide il 25/09/2026
   (clienti/screening-italia/copy/copy_*.md) e dal microcopy di MUSE (microcopy_sei_pagine.md).
   Chiave = ID casella: «<sezione>·<etichetta come scritta nel file di copy>».
   Estratte a macchina dai file .md, non ribattute: nessuna parola scritta in build. */

/* Non affiliazione al SSN: UN punto solo per gruppo (brief §1.4).
   ✅ Ratificate da LEX con vincoli il 25/09/2026.
   Formule riscritte da MUSE sui vincoli LEX del 25/09/2026, approvate da Davide il 25/09:
   microcopy_sei_pagine.md §5. */
window.SI_NON_AFFILIAZIONE = {
  adulti: "Screening Italia è un sito privato e indipendente. Non è affiliato né convenzionato con Servizio Sanitario Nazionale, Regioni, ASL, Ministero della Salute o Istituto Superiore di Sanità. Non parla a loro nome.",   // mammografico, cervicale, colon-retto, prostata
  genitori: "Screening Italia è un'iniziativa privata e indipendente. Non è affiliata né convenzionata con Servizio Sanitario Nazionale, Regioni, ASL, Ministero della Salute o Istituto Superiore di Sanità. Non parla a loro nome."  // neonatale, diabete-celiachia
};

/* Direttorio (N4, D5): dati per regione. Vuoti: [DATO MANCANTE — Angelo].
   Forma di una voce: neonatale["Lazio"] = { ente, laboratorio, tel }
                      diabete["Lazio"]   = [{ ente, stato: "attivo"|"in avvio"|"non attivo" }] */
window.SI_DIRETTORIO = { neonatale: {}, diabete: {} };

window.SCREENING_PAGINE = {
  "mammografico": {
    "S1·Occhiello": "SCREENING MAMMOGRAFICO",
    "S1·Titolo h1": "La lettera è arrivata. E adesso?",
    "S1·Sommario": "Se hai tra 50 e 69 anni, la ASL ti invita ogni due anni. L'esame è gratuito e non serve chiederlo. Decidi tu se andare.",
    "S1·Riga di orientamento": "Cosa arriva a casa e cosa succede dopo.",
    "S1·Etichetta CTA primaria": "Apri la tua regione",
    "S1·alt fotografia": "Una donna di circa sessant'anni legge a casa la lettera di invito allo screening.",
    "S2·Titolo h2": "Se hai tra 50 e 69 anni, ti riguarda",
    "S2·Paragrafo": "L'invito parte dagli elenchi dell'anagrafe sanitaria: non devi iscriverti. L'età di partenza cambia tra le regioni.",
    "S2·Cella 1 · h3": "Dai 50 ai 69 anni",
    "S2·Cella 1 · prosa": "È la fascia che il programma nazionale copre. Alcune regioni allargano l'invito prima o dopo.",
    "S2·Cella 1 · etichetta icona": "Fascia di età",
    "S2·Cella 2 · h3": "Ogni due anni",
    "S2·Cella 2 · prosa": "La ASL richiama a distanza di due anni. Tra un invito e l'altro non serve fare nulla.",
    "S2·Cella 2 · etichetta icona": "Cadenza",
    "S2·Cella 3 · h3": "Gratuito, senza ricetta",
    "S2·Cella 3 · prosa": "Non paghi niente e non serve l'impegnativa del medico. L'invito vale come accesso.",
    "S2·Cella 3 · etichetta icona": "Costo",
    "S3·Titolo h2": "Dalla busta all'appuntamento, quattro passi",
    "S3·Passo 1 · h3": "Arriva una busta con data e ora",
    "S3·Passo 1 · prosa": "Dentro trovi il giorno, l'orario e l'indirizzo del centro. In molte regioni l'appuntamento è già fissato per te.",
    "S3·Passo 2 · h3": "Se la data non ti va bene, si sposta",
    "S3·Passo 2 · prosa": "Sulla lettera c'è il numero del centro screening. Chiami e chiedi un'altra data: l'invito resta valido.",
    "S3·Passo 3 · h3": "Il giorno dell'esame porti la lettera",
    "S3·Passo 3 · prosa": "Servono la lettera e la tessera sanitaria. Non serve digiuno e non serve preparazione. L'esame dura pochi minuti.",
    "S3·Passo 4 · h3": "L'esito arriva a casa",
    "S3·Passo 4 · prosa": "La risposta arriva per posta o sul fascicolo sanitario. I tempi cambiano da regione a regione.",
    "S4·Titolo h2": "Dentro l'ambulatorio, passo per passo",
    "S4·Paragrafo": "Sapere prima cosa succede aiuta. L'esame lo fa una tecnica, in una stanza chiusa, e ci sei solo tu.",
    "S4·Voce 1": "Ti chiedono nome, data di nascita e la lettera.",
    "S4·Voce 2": "Ti spogli dalla vita in su, in uno spazio riservato.",
    "S4·Voce 3": "Il seno viene compresso per pochi secondi. Può dare fastidio.",
    "S4·Voce 4": "Finisce in pochi minuti e torni a casa. L'esito non te lo danno lì.",
    "S5·Titolo h2": "Come arriva la risposta, e in quanto tempo",
    "S5·Paragrafo": "Nella maggior parte dei casi l'esito è negativo e il prossimo invito arriva fra due anni. A volte il centro richiama per un controllo in più: serve a guardare meglio.",
    "S5·Riquadro · h3": "Richiamo non vuol dire tumore",
    "S5·Riquadro · prosa": "Il richiamo serve a chiarire un'immagine dubbia. Non è una diagnosi, e non anticipa nessun esito. Te lo spiega il medico del centro.",
    "S6·Titolo h2": "Non ti è arrivata la lettera?",
    "S6·Prosa": "Succede, e non è colpa tua. Sulla pagina dedicata trovi chi chiamare e cosa chiedere.",
    "S6·Etichetta bottone a contorno": "Lettera non arrivata",
    "S7·Titolo h2": "Le domande prima di andare",
    "S7·D1": "Posso andare se ho già fatto una mammografia privata?",
    "S7·R1": "L'invito resta valido. Se hai già fatto un esame di recente, chiama il centro screening: sono loro a dirti come fare.",
    "S7·D2": "L'esame fa male?",
    "S7·R2": "La compressione dura pochi secondi e può dare fastidio. Se senti dolore dillo subito alla tecnica: può cambiare posizione.",
    "S7·D3": "Posso spostare l'appuntamento?",
    "S7·R3": "Sì. Chiami il numero sulla lettera e chiedi un'altra data. Meglio farlo prima del giorno fissato, così il posto va a un'altra persona.",
    "S7·D4": "Ho più di 69 anni. Posso farlo lo stesso?",
    "S7·R4": "Fuori dalla fascia invitata non arriva la lettera. Alcune regioni allargano il programma: chiedi al centro screening della tua ASL come funziona lì.",
    "S8·Titolo h2": "Cosa si muove nella tua regione",
    "S8·Paragrafo": "Apri la tua regione: trovi le iniziative aperte adesso, con la data, il luogo e chi chiamare.",
    "S8-b·Titolo h2": "Nessuna iniziativa censita, per ora",
    "S8-b·Prosa": "Il programma di screening resta attivo lo stesso: l'invito arriva dalla ASL. Se conosci un'iniziativa sul territorio, segnalacela.",
    "S8-b·Etichetta piena": "Segnala un'iniziativa",
    "S8-b·Etichetta a contorno": "Torna alla mappa",
    "S9·Testo 17": "Screening Italia informa e basta. Non prenotiamo esami, non diamo pareri medici, non sostituiamo la tua ASL.",
    "S10·Titolo h2": "Altri articoli sullo screening del seno",
    "S10·Titolo articolo 1": "Cosa c'è scritto davvero nella lettera della ASL",
    "S10·Titolo articolo 2": "Perché al Sud si aderisce meno",
    "S10·Titolo articolo 3": "Chi riceve l'invito e chi resta fuori",
    "S11·Testo 17": "Le informazioni di questa pagina hanno scopo divulgativo. Non sostituiscono il parere del medico e non servono a interpretare un esame o un referto. Per quello c'è il tuo medico.",
    "Microtesti·Titolo per Google": "Screening mammografico: cosa arriva e cosa succede",
    "Microtesti·Descrizione per Google": "Hai tra 50 e 69 anni e la ASL ti invita alla mammografia. Cosa arriva a casa, come si svolge l'esame, quanto si aspetta la risposta.",
    "Microtesti·CTA · variante A": "Apri la tua regione",
    "Microtesti·CTA · variante B": "Vedi la tua regione",
    "Microtesti·CTA · variante C": "Scegli la tua regione"
  },
  "cervicale": {
    "S1·Occhiello": "SCREENING CERVICALE",
    "S1·Titolo h1": "Dal ginecologo ci vai già?",
    "S1·Sommario": "Tra i 25 e i 64 anni la ASL ti invita: Pap test fino a 30, HPV test dopo. È gratuito e l'invito basta.",
    "S1·Riga di orientamento": "Quale test ti tocca, e ogni quanto.",
    "S1·Etichetta CTA primaria": "Apri la tua regione",
    "S1·alt fotografia": "Una donna sulla quarantina apre la busta dell'invito allo screening, in cucina.",
    "S2·Titolo h2": "Due esami diversi, secondo l'età",
    "S2·Paragrafo": "Il programma nazionale copre dai 25 ai 64 anni. Cambia l'esame, cambia la cadenza: dipende da quanti anni hai.",
    "S2·Cella 1 · h3": "Dai 25 ai 29 anni: Pap test",
    "S2·Cella 1 · prosa": "Un prelievo di cellule dal collo dell'utero, ripetuto ogni tre anni. Lo fa un'ostetrica in ambulatorio.",
    "S2·Cella 1 · etichetta icona": "25-29 anni",
    "S2·Cella 2 · h3": "Dai 30 ai 64 anni: HPV test",
    "S2·Cella 2 · prosa": "Stesso prelievo, analisi diversa: cerca il virus HPV. Se è negativo, il richiamo arriva dopo cinque anni.",
    "S2·Cella 2 · etichetta icona": "30-64 anni",
    "S2·Cella 3 · h3": "Gratuito, senza ricetta",
    "S2·Cella 3 · prosa": "L'invito vale come accesso: non paghi e non serve l'impegnativa del medico di famiglia.",
    "S2·Cella 3 · etichetta icona": "Costo",
    "S2·Cella 4 · h3": "Se sei già in cura o in gravidanza",
    "S2·Cella 4 · prosa": "Chiama il centro screening prima di andare. Ti dicono loro se l'esame si fa adesso o più avanti.",
    "S2·Cella 4 · etichetta icona": "Casi particolari",
    "S3·Titolo h2": "Cosa arriva a casa, e in che ordine",
    "S3·Passo 1 · h3": "La lettera con data e orario",
    "S3·Passo 1 · prosa": "Arriva per posta e indica il consultorio o l'ambulatorio dove andare. In alcune regioni ricevi anche un SMS.",
    "S3·Passo 2 · h3": "Se il giorno non va bene",
    "S3·Passo 2 · prosa": "Sulla lettera c'è il numero da chiamare. Chiedi un'altra data: l'appuntamento si sposta senza perdere l'invito.",
    "S3·Passo 3 · h3": "Il giorno dell'esame",
    "S3·Passo 3 · prosa": "Porti lettera e tessera sanitaria. Il prelievo dura pochi minuti. Se hai il ciclo, chiama e sposta.",
    "S3·Passo 4 · h3": "La risposta arriva a casa",
    "S3·Passo 4 · prosa": "Se l'esito è negativo lo ricevi per posta o sul fascicolo sanitario. Se serve un controllo in più, ti chiama il centro.",
    "S4·Titolo h2": "Com'è fatto il prelievo",
    "S4·Paragrafo": "Il fastidio più grosso è l'imbarazzo, e passa se sai cosa succede. Nella stanza ci siete tu e chi fa il prelievo.",
    "S4·Voce 1": "Ti chiedono la lettera e la tessera sanitaria.",
    "S4·Voce 2": "Ti spogli dalla vita in giù, dietro un paravento.",
    "S4·Voce 3": "Il prelievo dura pochi secondi. Può dare fastidio.",
    "S4·Voce 4": "Ti rivesti e torni a casa. L'esito arriva dopo.",
    "S5·Titolo h2": "Se il test è positivo non è una diagnosi",
    "S5·Paragrafo": "Un HPV test positivo dice che il virus è presente. Non dice che c'è un tumore. Il centro ti richiama per un controllo in più, e te lo spiega il medico.",
    "S5·Riquadro · h3": "Positivo non vuol dire malata",
    "S5·Riquadro · prosa": "Il test cerca il virus. Non dice se c'è una malattia. Che cosa significa nel tuo caso lo dice il medico del centro.",
    "S5·Etichetta di rimando a /hpv/": "HPV: si può fare da sole?",
    "S6·Titolo h2": "Non ti è arrivata la lettera?",
    "S6·Prosa": "Succede, e non è colpa tua. Sulla pagina dedicata trovi chi chiamare e cosa chiedere.",
    "S6·Etichetta bottone a contorno": "Lettera non arrivata",
    "S7·Titolo h2": "Le domande prima di andare",
    "S7·D1": "Vado già dal ginecologo. Serve lo stesso?",
    "S7·R1": "Il programma della ASL è gratuito e segue una cadenza fissa. Se fai già controlli privati, parlane con chi ti segue e con il centro screening.",
    "S7·D2": "Ho fatto il vaccino HPV. Devo andare?",
    "S7·R2": "L'invito arriva anche a chi è vaccinata: il programma non esclude nessuna della fascia. Se hai dubbi, chiedi al centro screening della tua ASL.",
    "S7·D3": "Sono in menopausa. Mi riguarda ancora?",
    "S7·R3": "Sì, l'invito arriva fino a 64 anni. La menopausa non chiude il programma: la lettera continua ad arrivare.",
    "S7·D4": "Posso farlo se ho il ciclo?",
    "S7·R4": "Meglio chiamare e spostare di qualche giorno. Il numero è sulla lettera e l'invito resta valido.",
    "S8·Titolo h2": "Cosa si muove nella tua regione",
    "S8·Paragrafo": "Apri la tua regione: vedi le iniziative attive, dove sono e chi contattare.",
    "S8-b·Titolo h2": "Nessuna iniziativa censita, per ora",
    "S8-b·Prosa": "Il programma di screening resta attivo lo stesso: l'invito arriva dalla ASL. Se conosci un'iniziativa sul territorio, segnalacela.",
    "S8-b·Etichetta piena": "Segnala un'iniziativa",
    "S8-b·Etichetta a contorno": "Torna alla mappa",
    "S9·Testo 17": "Screening Italia informa e basta. Non prenotiamo esami, non diamo pareri medici, non sostituiamo la tua ASL.",
    "S10·Titolo h2": "Altri articoli sullo screening cervicale",
    "S10·Titolo articolo 1": "Pap test e HPV test: cosa cambia",
    "S10·Titolo articolo 2": "Cosa c'è scritto nella lettera della ASL",
    "S10·Titolo articolo 3": "Chi riceve l'invito e chi resta fuori",
    "S11·Testo 17": "Le informazioni di questa pagina hanno scopo divulgativo. Non sostituiscono il parere del medico e non servono a interpretare un esame o un referto. Per quello c'è il tuo medico.",
    "Microtesti·Titolo per Google": "Screening cervicale: Pap test e HPV test",
    "Microtesti·Descrizione per Google": "Tra i 25 e i 64 anni la ASL ti invita: Pap test o HPV test, gratuito. Cosa arriva a casa, come si svolge il prelievo, quando arriva la risposta.",
    "Microtesti·CTA · variante A": "Apri la tua regione",
    "Microtesti·CTA · variante B": "Vedi la tua regione",
    "Microtesti·CTA · variante C": "Scegli la tua regione"
  },
  "colon-retto": {
    "S1·Occhiello": "SCREENING COLON-RETTO",
    "S1·Titolo h1": "Il kit arriva per posta",
    "S1·Sommario": "Dai 50 ai 69 anni la ASL ti manda un kit da fare a casa. Raccogli un campione, lo riporti, è gratuito.",
    "S1·Riga di orientamento": "Come si fa e dove si riporta il kit.",
    "S1·Etichetta CTA primaria": "Apri la tua regione",
    "S1·alt fotografia": "La scatola del kit per lo screening del colon appoggiata sul tavolo, accanto alla lettera.",
    "S2·Titolo h2": "Se hai tra 50 e 69 anni, ti riguarda",
    "S2·Paragrafo": "Il kit parte dagli elenchi dell'anagrafe sanitaria: non devi chiederlo. L'età di arrivo cambia tra le regioni.",
    "S2·Cella 1 · h3": "Dai 50 ai 69 anni",
    "S2·Cella 1 · prosa": "È la fascia coperta dal programma nazionale. Alcune regioni invitano anche dopo i 69 anni.",
    "S2·Cella 1 · etichetta icona": "Fascia di età",
    "S2·Cella 2 · h3": "Ogni due anni",
    "S2·Cella 2 · prosa": "Se l'esito è regolare, il kit torna dopo due anni. Nel frattempo non devi fare niente.",
    "S2·Cella 2 · etichetta icona": "Cadenza",
    "S2·Cella 3 · h3": "Gratuito, senza ricetta",
    "S2·Cella 3 · prosa": "Il kit non si paga e non serve l'impegnativa. Anche l'analisi in laboratorio è compresa.",
    "S2·Cella 3 · etichetta icona": "Costo",
    "S3·Titolo h2": "Dal kit al risultato, quattro passi",
    "S3·Passo 1 · h3": "Arriva la lettera con il kit",
    "S3·Passo 1 · prosa": "In molte regioni il kit si ritira in farmacia o al distretto: la lettera dice dove e in che orari.",
    "S3·Passo 2 · h3": "Raccogli il campione a casa",
    "S3·Passo 2 · prosa": "Dentro trovi una provetta e il foglio con le istruzioni. Serve un campione solo, e si fa in bagno in pochi minuti.",
    "S3·Passo 3 · h3": "Riporti la provetta dove ti dicono",
    "S3·Passo 3 · prosa": "Farmacia, distretto o punto di raccolta: la lettera indica il posto. Meglio riportarla entro il giorno indicato.",
    "S3·Passo 4 · h3": "L'esito arriva a casa",
    "S3·Passo 4 · prosa": "Se il test è negativo lo ricevi per posta. Se trova tracce di sangue, il centro ti chiama per un esame di controllo.",
    "S4·Titolo h2": "Come si fa il test, a casa",
    "S4·Paragrafo": "Il foglio dentro la scatola spiega tutto. Qui c'è la versione corta, per capire prima di aprire il kit.",
    "S4·Voce 1": "Scrivi nome e data sull'etichetta della provetta.",
    "S4·Voce 2": "Raccogli il campione con il bastoncino incluso.",
    "S4·Voce 3": "Non serve dieta e non serve digiuno.",
    "S4·Voce 4": "Chiudi la provetta e segui il foglio per conservarla.",
    "S4·Voce 5": "Riporti la provetta nel punto indicato sulla lettera.",
    "S5·Titolo h2": "Se trova sangue non vuol dire tumore",
    "S5·Paragrafo": "Il test cerca tracce di sangue non visibili. Il sangue può venire da un polipo o da un'emorroide, e per questo il centro propone una colonscopia di controllo.",
    "S5·Riquadro · h3": "Essere richiamati non è una diagnosi",
    "S5·Riquadro · prosa": "Il richiamo serve a guardare dentro con la colonscopia. Cosa significa nel tuo caso lo dice il medico che ti segue.",
    "S6·Titolo h2": "Non ti è arrivata la lettera?",
    "S6·Prosa": "Succede, e non è colpa tua. Sulla pagina dedicata trovi chi chiamare e cosa chiedere.",
    "S6·Etichetta bottone a contorno": "Lettera non arrivata",
    "S7·Titolo h2": "Le domande prima di farlo",
    "S7·D1": "Ho buttato il kit. Posso averne un altro?",
    "S7·R1": "Sì. Chiami il centro screening della tua ASL con la tessera sanitaria a portata di mano e chiedi un nuovo kit.",
    "S7·D2": "Devo fare una dieta prima?",
    "S7·R2": "No. Le istruzioni del kit non chiedono nessuna dieta e nessun digiuno. Se hai dubbi, il numero del centro screening è sulla lettera.",
    "S7·D3": "Devo riportarlo di persona?",
    "S7·R3": "Può portarlo anche un familiare. Conta che arrivi al punto di raccolta indicato, negli orari scritti sulla lettera.",
    "S7·D4": "Ho più di 69 anni. Mi mandano il kit?",
    "S7·R4": "Dipende dalla regione: alcune invitano oltre i 69 anni, altre no. Il centro screening della tua ASL ti dice come funziona lì.",
    "S8·Titolo h2": "Cosa si muove nella tua regione",
    "S8·Paragrafo": "Apri la tua regione: trovi le iniziative aperte adesso, con la data, il luogo e chi chiamare.",
    "S8-b·Titolo h2": "Nessuna iniziativa censita, per ora",
    "S8-b·Prosa": "Il programma di screening resta attivo lo stesso: l'invito arriva dalla ASL. Se conosci un'iniziativa sul territorio, segnalacela.",
    "S8-b·Etichetta piena": "Segnala un'iniziativa",
    "S8-b·Etichetta a contorno": "Torna alla mappa",
    "S9·Testo 17": "Screening Italia informa e basta. Non prenotiamo esami, non diamo pareri medici, non sostituiamo la tua ASL.",
    "S10·Titolo h2": "Altri articoli sullo screening del colon",
    "S10·Titolo articolo 1": "Perché il kit resta nel cassetto",
    "S10·Titolo articolo 2": "Cosa c'è scritto nella lettera della ASL",
    "S10·Titolo articolo 3": "Chi riceve l'invito e chi resta fuori",
    "S11·Testo 17": "Le informazioni di questa pagina hanno scopo divulgativo. Non sostituiscono il parere del medico e non servono a interpretare un esame o un referto. Per quello c'è il tuo medico.",
    "Microtesti·Titolo per Google": "Screening colon-retto: il kit che arriva a casa",
    "Microtesti·Descrizione per Google": "Dai 50 ai 69 anni la ASL manda a casa un kit gratuito per il sangue occulto. Come si fa, dove si riporta, cosa succede dopo.",
    "Microtesti·CTA · variante A": "Apri la tua regione",
    "Microtesti·CTA · variante B": "Vedi la tua regione",
    "Microtesti·CTA · variante C": "Scegli la tua regione"
  },
  "prostata": {
    "S1·Occhiello": "PROSTATA E PSA",
    "S1·Titolo h1": "Per la prostata non esiste un invito",
    "S1·Sommario": "In Italia non c'è un programma nazionale che invita gli uomini a fare il PSA. Alcune regioni hanno avviato progetti propri. Qui trovi cosa esiste e cosa no.",
    "S1·Riga di orientamento": "Cosa esiste oggi, e cosa puoi chiedere.",
    "S1·Etichetta CTA primaria": "Apri la tua regione",
    "S1·alt fotografia": "Un uomo sui sessant'anni cerca informazioni sullo schermo del telefono, seduto in cucina.",
    "S2·Titolo h2": "Dopo i 50 la domanda arriva da sola",
    "S2·Paragrafo": "Il PSA è un esame del sangue, e si può fare in qualsiasi momento. Quando farlo e se farlo lo decidi con il tuo medico.",
    "S2·Cella 1 · h3": "Dai 50 anni in su",
    "S2·Cella 1 · prosa": "È l'età da cui partono i progetti regionali, dove esistono. Sotto i 50 non sono previsti.",
    "S2·Cella 1 · etichetta icona": "Fascia di età",
    "S2·Cella 2 · h3": "Nessuna cadenza fissa",
    "S2·Cella 2 · prosa": "Senza un programma nazionale non c'è un ritmo stabilito. Lo decide il medico che ti segue.",
    "S2·Cella 2 · etichetta icona": "Cadenza",
    "S2·Cella 3 · h3": "Il costo dipende",
    "S2·Cella 3 · prosa": "Fuori dai progetti regionali il PSA si paga con il ticket o in privato. Dentro un progetto è gratuito.",
    "S2·Cella 3 · etichetta icona": "Costo",
    "S2-bis·Titolo h2": "Perché non ti arriva nessun invito",
    "S2-bis·Paragrafo": "I tre screening con invito hanno un programma nazionale alle spalle. Sulla prostata quel programma non c'è, quindi nessuna ASL manda lettere.",
    "S2-bis·Voce 1": "Non esiste una lettera da aspettare.",
    "S2-bis·Voce 2": "La decisione parte da te e dal tuo medico.",
    "S2-bis·Voce 3": "Alcune regioni stanno provando programmi locali.",
    "S3·Titolo h2": "Dove è partito un programma regionale",
    "S3·Passo 1 · h3": "Guarda se la tua regione ha un progetto",
    "S3·Passo 1 · prosa": "Apri la tua regione qui sotto. Se un progetto è attivo, trovi l'ente che lo tiene e chi contattare.",
    "S3·Passo 2 · h3": "Parla con il tuo medico di famiglia",
    "S3·Passo 2 · prosa": "È lui che conosce la tua storia e che può indirizzarti. Porta le domande scritte: si fa prima.",
    "S3·Passo 3 · h3": "Chiedi cosa comprende il progetto",
    "S3·Passo 3 · prosa": "Chi può entrare, quali esami sono inclusi, se si paga qualcosa. Sono le tre cose che cambiano di più.",
    "S3·Passo 4 · h3": "Se nella tua regione non c'è niente",
    "S3·Passo 4 · prosa": "Resta la strada normale: ne parli con il medico e, se serve, con un urologo. Il PSA si può fare anche fuori da un progetto.",
    "S4·Titolo h2": "Il PSA in pratica: cosa comporta",
    "S4·Paragrafo": "È un prelievo di sangue come gli altri. Quello che serve sapere sta dopo: chi legge il risultato e cosa ci fa.",
    "S4·Voce 1": "Serve una richiesta del medico, se lo fai col ticket.",
    "S4·Voce 2": "Il prelievo dura pochi minuti, in laboratorio.",
    "S4·Voce 3": "Il referto arriva in pochi giorni.",
    "S4·Voce 4": "Il numero da solo non dice niente: lo legge il medico.",
    "S5·Titolo h2": "Cosa succede dopo il referto",
    "S5·Paragrafo": "Il valore va letto insieme ad altri dati. Qui non trovi soglie e non trovi interpretazioni. Il referto si porta al medico, che decide con te il passo dopo.",
    "S5·Riquadro · h3": "Un PSA alto non vuol dire tumore",
    "S5·Riquadro · prosa": "Il valore può salire per ragioni diverse. Cosa significa nel tuo caso lo dice il medico, guardando la tua storia.",
    "S6·Titolo h2": "Per gli altri screening la lettera arriva",
    "S6·Prosa": "Mammella, cervice e colon hanno l'invito della ASL. Se a te non è arrivato, si può rientrare.",
    "S6·Etichetta bottone a contorno": "Lettera non arrivata",
    "S7·Titolo h2": "Le domande prima di decidere",
    "S7·D1": "Devo fare il PSA ogni anno?",
    "S7·R1": "Non esiste una cadenza nazionale. Ogni quanto ripeterlo, e se ripeterlo, lo decide il medico che ti segue.",
    "S7·D2": "Il PSA è gratuito?",
    "S7·R2": "Fuori da un progetto regionale si paga il ticket, salvo esenzioni. Dentro un progetto è gratuito.",
    "S7·D3": "Mio padre ha avuto un tumore alla prostata.",
    "S7·R3": "Dillo al tuo medico: è un'informazione che gli serve. Non è una risposta che possiamo darti noi.",
    "S7·D4": "Il mio valore è 4,5. È alto?",
    "S7·R4": "Su questo sito non interpretiamo nessun valore, e nessun numero vale uguale per tutti. Il referto si legge insieme al medico.",
    "S7·D5": "Perché non fanno uno screening nazionale?",
    "S7·R5": "La scelta di attivare un programma di popolazione spetta alle istituzioni sanitarie. Oggi in Italia si muovono le singole regioni.",
    "S7·D6": "Posso farlo anche senza sintomi?",
    "S7·R6": "Il PSA si può fare anche senza disturbi. Se ha senso farlo adesso lo valuti con il medico, che conosce la tua storia.",
    "S8·Titolo h2": "Cosa si muove nella tua regione",
    "S8·Paragrafo": "Apri la tua regione: se esiste un progetto sulla prostata lo trovi qui, con l'ente e il recapito.",
    "S8-b·Titolo h2": "Nessuna iniziativa censita, per ora",
    "S8-b·Prosa": "Non abbiamo ancora censito progetti in questa regione. Se ne conosci uno, segnalacelo e lo pubblichiamo.",
    "S8-b·Etichetta piena": "Segnala un'iniziativa",
    "S8-b·Etichetta a contorno": "Torna alla mappa",
    "S9·Testo 17": "Screening Italia informa e basta. Non prenotiamo esami, non diamo pareri medici, non sostituiamo la tua ASL.",
    "S10·Titolo h2": "Altri articoli su prostata e PSA",
    "S10·Titolo articolo 1": "PSA: cosa misura e cosa no",
    "S10·Titolo articolo 2": "Perché la prostata non ha un invito",
    "S10·Titolo articolo 3": "Gli screening con invito: chi li riceve",
    "S11·Testo 17": "Le informazioni di questa pagina hanno scopo divulgativo. Non sostituiscono il parere del medico e non servono a interpretare un esame o un referto. Per quello c'è il tuo medico.",
    "Microtesti·Titolo per Google": "Screening prostata: cosa esiste in Italia",
    "Microtesti·Descrizione per Google": "Per la prostata non esiste un programma nazionale con invito. Cosa c'è oggi, come funziona il PSA e cosa chiedere al tuo medico.",
    "Microtesti·CTA · variante A": "Apri la tua regione",
    "Microtesti·CTA · variante B": "Vedi la tua regione",
    "Microtesti·CTA · variante C": "Scegli la tua regione"
  },
  "neonatale": {
    "N1·Occhiello": "SCREENING NEONATALE",
    "N1·Titolo h1": "Il test del tallone: cosa cerca",
    "N1·Sommario": "A tuo figlio hanno punto il tallone in ospedale, nei primi giorni. È uno screening: cerca malattie rare che alla nascita non si vedono. Non lo decidi tu: vale per tutti.",
    "N1·Riquadro · titolo h3": "Dovevi chiedere qualcosa? No.",
    "N1·Riquadro · prosa": "Il prelievo si fa in ospedale, con una goccia di sangue dal tallone, di solito entro 48-72 ore dalla nascita. È gratuito. Non si chiede e non si prenota: fa parte delle cure alla nascita.",
    "N2·Titolo h2": "Cerca quello che alla nascita non si vede",
    "N2·Paragrafo": "Sono malattie rare, presenti dalla nascita. Un bambino può stare benissimo e averne una: i segnali arrivano più tardi. Trovate subito, si curano prima che facciano danno. Per questo il test si fa a tutti.",
    "N2·Voce puntata 1": "Condizioni che alla nascita non danno sintomi",
    "N2·Voce puntata 2": "Malattie rare, dove i primi mesi contano",
    "N2·Voce puntata 3": "Una sola goccia di sangue, per tutte insieme",
    "N2·Voce puntata 4": "L'elenco preciso lo tiene il centro della tua regione",
    "N3·Titolo h2": "Se ti richiamano per un secondo prelievo",
    "N3·Paragrafo": "Capita che il laboratorio chieda un secondo campione. Il primo valore è fuori dall'intervallo atteso e serve un controllo. Il motivo può essere tecnico: poco sangue sul cartoncino, prelievo fatto molto presto. Chi ti ha chiamato dice cosa fare e dove andare.",
    "N3·Riquadro · titolo h3": "Un richiamo non è una diagnosi",
    "N3·Riquadro · prosa": "Il primo test è un filtro largo: segnala tutto quello che merita un controllo, anche quando poi non c'è niente. Il secondo prelievo serve a chiarire. Prima del risultato non c'è diagnosi.",
    "N3·Voce puntata 1": "Il secondo prelievo si fa come il primo",
    "N3·Voce puntata 2": "Chiedi al centro in quanti giorni arriva l'esito",
    "N3·Voce puntata 3": "Porta il foglio del richiamo a ogni visita",
    "N4·Titolo h2": "Il centro di riferimento della tua regione",
    "N4·Paragrafo": "Ogni regione ha un centro di screening neonatale e un laboratorio che analizza i campioni. Sono loro a rispondere. Cerca la tua.",
    "N4·Scheda · che cos'è, in una riga": "Segue lo screening neonatale in regione",
    "N4·Scheda · etichetta laboratorio": "ANALISI",
    "N4·Scheda · nota": "Qui trovi a chi chiedere. Per gli appuntamenti serve il pediatra.",
    "N5·Titolo h2": "A chi chiedere, in quest'ordine",
    "N5·Passo 1 · titolo h3": "Il punto nascita dove è nato",
    "N5·Passo 1 · prosa": "Ha fatto il prelievo e conserva la data. Chiedi in reparto o alla segreteria del punto nascita.",
    "N5·Passo 2 · titolo h3": "Il pediatra di libera scelta",
    "N5·Passo 2 · prosa": "Vede il bambino dai primi giorni e legge i documenti dell'ospedale. È la persona giusta per capire cosa è già stato fatto.",
    "N5·Passo 3 · titolo h3": "Il centro di screening della regione",
    "N5·Passo 3 · prosa": "Risponde sul programma, sui tempi e su un richiamo arrivato. Chiama dopo aver parlato con il pediatra.",
    "N5·Passo 4 · titolo h3": "Le associazioni di famiglie",
    "N5·Passo 4 · prosa": "Per le malattie rare esistono associazioni che seguono le famiglie da anni. Il centro regionale sa indicare quella giusta.",
    "N6·Titolo h2": "Le domande che fanno i genitori",
    "N6·Domanda 1": "Il test si fa a tutti i bambini?",
    "N6·Risposta 1": "Sì. Fa parte delle cure alla nascita e si esegue in ospedale, senza che i genitori lo chiedano. Se hai dubbi su come è andata, il punto nascita ha la documentazione.",
    "N6·Domanda 2": "Quanto tempo dopo la nascita si fa?",
    "N6·Risposta 2": "Di solito fra le 48 e le 72 ore di vita. L'orario preciso lo decide il reparto in base alla nascita. La data è nei documenti dell'ospedale.",
    "N6·Domanda 3": "Dove trovo il risultato?",
    "N6·Risposta 3": "Quando il risultato rientra nei valori attesi, di solito non arriva nessuna comunicazione. Se ti serve il documento, lo chiedi al punto nascita o al centro regionale.",
    "N6·Domanda 4": "Serve rifare il test più avanti?",
    "N6·Risposta 4": "Lo screening alla nascita si fa una volta sola. Altri controlli dipendono dalla storia del bambino e li valuta il pediatra, visita dopo visita.",
    "N6·Domanda 5": "Il test costa qualcosa?",
    "N6·Risposta 5": "No. Fa parte del percorso nascita e non compare in nessun conto. Non serve impegnativa e non si paga il ticket.",
    "N6·Domanda 6": "Posso rifiutare il prelievo?",
    "N6·Risposta 6": "È una domanda da porre in reparto, prima della dimissione. Il personale spiega cosa prevede il programma e che cosa comporta la scelta.",
    "N7·Titolo h2": "Se il bambino deve ancora nascere",
    "N7·Paragrafo": "Il prelievo verrà fatto in ospedale, nei primi giorni, senza che tu debba organizzare niente. Sapere che esiste serve a una cosa: riconoscere il foglio, se arriva.",
    "N7·Voce puntata 1": "Chiedi al punto nascita come funziona da loro",
    "N7·Voce puntata 2": "Scegli il pediatra nelle prime settimane di vita",
    "N7·Voce puntata 3": "Tieni i documenti della dimissione in un posto solo",
    "N8": "Questa pagina ha scopo informativo e non sostituisce il parere del medico. Per una valutazione sul singolo bambino rivolgiti al pediatra o al centro di riferimento. Non interpretiamo esiti.",
    "N9": "Non prenotiamo esami, non leggiamo referti, non diamo consigli medici. Raccogliamo informazioni pubbliche e indichiamo a chi chiedere.",
    "Microtesti·Titolo per Google": "Screening neonatale: il test del tallone, spiegato",
    "Microtesti·Descrizione per Google": "A tuo figlio hanno punto il tallone in ospedale: cosa cerca quel test, cosa succede se arriva un richiamo e a chi chiedere nella tua regione.",
    "Microtesti·alt della fotografia di apertura": "Un neonato in braccio a un genitore, in ospedale",
    "Microtesti·Etichetta del bottone del direttorio · variante 1": "Trova il centro regionale",
    "Microtesti·Etichetta del bottone del direttorio · variante 2": "Apri la tua regione",
    "Microtesti·Etichetta del bottone del direttorio · variante 3": "Vedi il centro della tua zona",
    "Microtesti·Etichetta del recapito telefonico": "Chiama il centro"
  },
  "diabete-celiachia": {
    "D1·Occhiello": "DIABETE TIPO 1 E CELIACHIA",
    "D1·Titolo h1": "C'è una legge, e riguarda tuo figlio",
    "D1·Sommario": "Dal 2023 in Italia esiste uno screening per il diabete tipo 1 e la celiachia nei bambini. Il percorso passa dal pediatra. Non arriva nessuna lettera: la chiedi tu.",
    "D1·Riquadro · prosa (L. 130/2023)": "La Legge 130 del 2023 ha istituito uno screening pediatrico per il diabete tipo 1 e la celiachia. È la prima legge di questo tipo al mondo. Cerca i segni della malattia prima dei sintomi.",
    "D2·Titolo h2": "A chi tocca, e quando",
    "D2·Paragrafo": "Lo screening riguarda i bambini, in fasce d'età definite dal programma nazionale. Non parte da una lettera: parte da chi segue tuo figlio. Il pediatra dice se tuo figlio rientra, e come si procede.",
    "D2·Voce puntata 1": "Prima fascia d'età: [DATO MANCANTE: età prevista dal programma]",
    "D2·Voce puntata 2": "Seconda fascia d'età: [DATO MANCANTE: età prevista]",
    "D2·Voce puntata 3": "Il pediatra conferma le età valide oggi",
    "D2·Riga di cautela": "Le età sono quelle previste dal programma. Non sono un appuntamento fissato per tuo figlio.",
    "D3·Titolo h3": "A che punto è, oggi",
    "D3·Prosa: a che punto è l'attuazione": "Qui scriviamo a che punto è il programma, senza interpretarlo. [DATO MANCANTE: stato dell'attuazione, fonte istituzionale]",
    "D3·Data di aggiornamento": "Aggiornato il 17 settembre 2026",
    "D3·Nota": "La data dice quando abbiamo controllato. [DA DECIDERE · ANGELO: cadenza]",
    "D4·Titolo h2": "La domanda da fare al pediatra",
    "D4·Paragrafo": "Non serve sapere niente di più. Alla prossima visita, o al telefono, si chiede questo.",
    "D4·La frase da ripetere in ambulatorio": "«Mio figlio rientra nello screening per diabete e celiachia?»",
    "D4·Nota sotto la frase": "Se la risposta non è chiara, chiedi chi in ASL segue il programma.",
    "D5·Titolo h2": "Dove il programma è già partito",
    "D5·Paragrafo": "Qui teniamo l'elenco dei centri e degli enti che hanno avviato il programma. Non si prenota da qui: si chiede al pediatra.",
    "D5·Scheda · etichetta di stato": "attivo · in avvio · non attivo",
    "D5·Scheda · nota": "Ogni voce dice il nome dell'ente e lo stato del programma.",
    "D6·Titolo h2": "Se l'esito dice che c'è qualcosa",
    "D6·Paragrafo": "Un esito positivo non vuol dire che il bambino è malato oggi. Vuol dire che verrà seguito: controlli programmati, un centro di riferimento, una famiglia che sa cosa guardare. Se un giorno la malattia si manifesta, non coglie nessuno di sorpresa.",
    "D6·Riquadro · titolo h3": "Positivo non vuol dire malato",
    "D6·Riquadro · prosa": "Lo screening segnala chi va seguito. La diagnosi arriva dopo, da esami specialistici, e la fa un medico. Da quel momento la famiglia sa cosa osservare e chi chiamare.",
    "D6·Spiegazione sotto il numero": "È il calo dei casi gravi all'esordio nel programma pilota. Accorgersene prima cambia il modo in cui la malattia comincia.",
    "D7·Titolo h2": "Le domande che fanno i genitori",
    "D7·Domanda 1": "Chi fa la richiesta?",
    "D7·Risposta 1": "Il pediatra di libera scelta. È lui che conosce il bambino, ha i documenti e avvia il percorso previsto dal programma.",
    "D7·Domanda 2": "Mio figlio sta bene: serve lo stesso?",
    "D7·Risposta 2": "Lo screening si rivolge proprio ai bambini che stanno bene. Cerca i segni che compaiono prima dei sintomi, quando ancora non c'è niente da vedere.",
    "D7·Domanda 3": "Il test è obbligatorio?",
    "D7·Risposta 3": "No. Il programma prevede un'offerta ai genitori, che decidono. Il pediatra spiega cosa comporta la scelta, in un senso e nell'altro.",
    "D7·Domanda 4": "Quanto costa?",
    "D7·Risposta 4": "Il programma è pubblico. Su costi e modalità la risposta esatta la dà il pediatra o l'ASL di appartenenza.",
    "D7·Domanda 5": "Che cos'è la celiachia, in breve?",
    "D7·Risposta 5": "È una reazione permanente al glutine che danneggia l'intestino. Nei bambini può restare silenziosa per anni. Il pediatra spiega cosa comporta la diagnosi.",
    "D7·Domanda 6": "Se il pediatra non ne ha mai parlato?",
    "D7·Risposta 6": "Chiedi tu, alla prima occasione. La legge è recente e il programma sta entrando nella pratica di tutti i giorni: la domanda del genitore serve.",
    "D8": "Questa pagina ha scopo informativo e non sostituisce il parere del medico. Per il singolo bambino la valutazione spetta al pediatra. Non interpretiamo esiti e non diamo indicazioni di cura.",
    "D9": "Non prenotiamo esami, non leggiamo referti, non diamo consigli medici. Raccogliamo informazioni pubbliche e indichiamo a chi chiedere.",
    "Microtesti·Titolo per Google": "Diabete tipo 1 e celiachia: lo screening dei bambini",
    "Microtesti·Descrizione per Google": "Dal 2023 in Italia esiste uno screening per diabete tipo 1 e celiachia nei bambini. Cosa prevede, a chi tocca e la domanda da fare al pediatra.",
    "Microtesti·alt della fotografia di apertura": "Un bambino in ambulatorio con il pediatra",
    "Microtesti·Etichetta del bottone · variante 1": "Porta la domanda al pediatra",
    "Microtesti·Etichetta del bottone · variante 2": "Vedi dov'è partito",
    "Microtesti·Etichetta del bottone · variante 3": "Apri la tua regione"
  }
};

/* Home «Tipologie di screening», link di ritorno, stati vuoti del direttorio (MUSE, 25/09/2026). */
window.SCREENING_MICRO = {
  "H·Titolo h2": "Quale screening ti riguarda",
  "H·Card 1 · mammografico · Titolo": "Screening mammografico",
  "H·Card 1 · mammografico · Riga": "Donne tra 50 e 69 anni. La ASL invita ogni due anni. L'esame è gratuito.",
  "H·Card 2 · cervicale · Titolo": "Screening cervicale",
  "H·Card 2 · cervicale · Riga": "Donne tra 25 e 64 anni. Pap test fino a 30, HPV test dopo. È gratuito.",
  "H·Card 3 · colon-retto · Titolo": "Screening colon-retto",
  "H·Card 3 · colon-retto · Riga": "Dai 50 ai 69 anni la ASL ti manda a casa un kit. È gratuito.",
  "H·Card 4 · prostata · Titolo": "Prostata e PSA",
  "H·Card 4 · prostata · Riga": "Non c'è un invito nazionale. Alcune regioni hanno progetti propri.",
  "H·Card 5 · neonatale · Titolo": "Screening neonatale",
  "H·Card 5 · neonatale · Riga": "Il test del tallone si fa in ospedale, a ogni neonato. Qui trovi cosa cerca.",
  "H·Card 6 · diabete-celiachia · Titolo": "Diabete tipo 1 e celiachia",
  "H·Card 6 · diabete-celiachia · Riga": "Dal 2023 una legge prevede uno screening per i bambini. Si chiede al pediatra.",
  "R·Link": "← Torna a tutti gli screening",
  "N4-b·Titolo h3": "Per questa regione non abbiamo ancora il centro",
  "N4-b·Prosa": "Lo aggiungiamo appena troviamo una fonte pubblica. Intanto chiedi al punto nascita o al pediatra.",
  "D5-b·Titolo h3": "Per questa regione non abbiamo ancora dati",
  "D5-b·Prosa": "Il programma può essere già partito anche se qui non compare. Chiedi al pediatra a che punto è."
};
